package parqueo.gui.frames.clientes;

import javax.swing.JOptionPane;
import parqueo.backend.excepciones.InputsVaciosException;
import parqueo.backend.excepciones.ValidacionExcepcion;
import parqueo.backend.modelos.personas.Cliente;
import parqueo.backend.personas.clientes.ManejadorClientes;

/**
 *
 * @author jose
 */
public class ClienteDataDialog extends javax.swing.JDialog {

	private ManejadorClientes manejadorClientes;
	private Cliente cliente;
	private boolean editar;
	private String nitSeleccionado;
	private String cuiSeleccionado;

	/**
	 * Creates new form NuevoEmpleadoDialog
	 */
	public ClienteDataDialog(boolean modal, ManejadorClientes manejador) {
		this.manejadorClientes = manejador;
		initComponents();
		this.setModal(modal);
	}

	public Cliente getCliente() {
		return cliente;
	}

	private void setCliente(Cliente cliente) {
		Cliente anterior = this.cliente;
		this.cliente = cliente;
		firePropertyChange("cliente", anterior, this.cliente);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          CUILabel = new javax.swing.JLabel();
          nombreLabel = new javax.swing.JLabel();
          guardarButton = new javax.swing.JButton();
          cancelarButton = new javax.swing.JButton();
          CUILabel1 = new javax.swing.JLabel();
          nitText = new javax.swing.JTextField();
          cuiText = new javax.swing.JTextField();
          nombreText = new javax.swing.JTextField();

          setTitle("Datos de empleado");
          setAlwaysOnTop(true);
          setResizable(false);

          CUILabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          CUILabel.setText("NIT");

          nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          nombreLabel.setText("Nombre completo:");

          guardarButton.setText("Guardar");
          guardarButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    guardarButtonActionPerformed(evt);
               }
          });

          cancelarButton.setText("Cancelar");
          cancelarButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cancelarButtonActionPerformed(evt);
               }
          });

          CUILabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          CUILabel1.setText("CUI:");

          org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.NIT}"), nitText, org.jdesktop.beansbinding.BeanProperty.create("text"));
          bindingGroup.addBinding(binding);

          binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.CUI}"), cuiText, org.jdesktop.beansbinding.BeanProperty.create("text"));
          bindingGroup.addBinding(binding);

          binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.nombre}"), nombreText, org.jdesktop.beansbinding.BeanProperty.create("text"));
          bindingGroup.addBinding(binding);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addGap(0, 297, Short.MAX_VALUE)
                              .addComponent(cancelarButton)
                              .addGap(18, 18, 18)
                              .addComponent(guardarButton))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(CUILabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(nitText))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(nombreText))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(CUILabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(cuiText)))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(CUILabel)
                         .addComponent(nitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(CUILabel1)
                         .addComponent(cuiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(nombreLabel)
                         .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(guardarButton)
                         .addComponent(cancelarButton))
                    .addContainerGap())
          );

          bindingGroup.bind();

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
		setCliente(null);
		this.setVisible(false);
     }//GEN-LAST:event_cancelarButtonActionPerformed

     private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
		try {
			if (!editar) {
				this.cliente = manejadorClientes.agregarCliente(nitText.getText(),
					   cuiText.getText(), nombreText.getText());
			} else {
				manejadorClientes.modificarCliente(nitSeleccionado, cuiSeleccionado, cliente);
			}
			///aqui
			setVisible(false);
		} catch (ValidacionExcepcion ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		} catch (InputsVaciosException ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}

     }//GEN-LAST:event_guardarButtonActionPerformed

	private void limpiar() {
		cuiText.setText("");
		nombreText.setText("");
		nitText.setText("");
	}

	public void mostrarParaCrear() {
		this.setTitle("Crear cliente");
		this.setVisible(true);
		this.editar = false;
	}

	public void mostrarParaEditar(Cliente clienteAEditar) {
		nitSeleccionado = clienteAEditar.getNIT();
		cuiSeleccionado = clienteAEditar.getCUI();
		setCliente(clienteAEditar);
		this.setTitle("Modificar Cliente");
		this.editar = true;
		this.setVisible(true);
	}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel CUILabel;
     private javax.swing.JLabel CUILabel1;
     private javax.swing.JButton cancelarButton;
     private javax.swing.JTextField cuiText;
     private javax.swing.JButton guardarButton;
     private javax.swing.JTextField nitText;
     private javax.swing.JLabel nombreLabel;
     private javax.swing.JTextField nombreText;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables
}
