/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueo.gui.frames.reportes;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import parqueo.backend.modelos.registros.RegistroVehiculo;
import parqueo.backend.reportes.Reporteador;

/**
 *
 * @author jose
 */
public class Reporte2InternalFrame extends javax.swing.JInternalFrame {

	private Reporteador reporteador;
	private List<RegistroVehiculo> registrosList;
	private ObservableList<RegistroVehiculo> registros;
	/**
	 * Creates new form Reporte2InternalFrame
	 */
	public Reporte2InternalFrame(Reporteador reporteador) {
		this.reporteador = reporteador;
		this.registrosList = new ArrayList<>();
		this.registros = ObservableCollections.observableList(registrosList);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          mostrarButton = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          jTable1 = new javax.swing.JTable();
          fechaFinText = new javax.swing.JFormattedTextField();
          fechaIniText = new javax.swing.JFormattedTextField();
          Inicio = new javax.swing.JLabel();
          Inicio1 = new javax.swing.JLabel();
          jLabel1 = new javax.swing.JLabel();
          totalLabel = new javax.swing.JLabel();

          setClosable(true);
          setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
          setIconifiable(true);
          setMaximizable(true);

          mostrarButton.setText("Mostrar reporte");
          mostrarButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mostrarButtonActionPerformed(evt);
               }
          });

          org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${registros}");
          org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
          org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliente.NIT}"));
          columnBinding.setColumnName("Cliente");
          columnBinding.setColumnClass(String.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaIngreso}"));
          columnBinding.setColumnName("Fecha");
          columnBinding.setColumnClass(java.time.LocalDate.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total}"));
          columnBinding.setColumnName("Total");
          columnBinding.setColumnClass(Double.class);
          columnBinding.setEditable(false);
          bindingGroup.addBinding(jTableBinding);
          jTableBinding.bind();
          jScrollPane1.setViewportView(jTable1);

          try {
               fechaFinText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
          } catch (java.text.ParseException ex) {
               ex.printStackTrace();
          }

          try {
               fechaIniText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
          } catch (java.text.ParseException ex) {
               ex.printStackTrace();
          }

          Inicio.setText("Inicio");

          Inicio1.setText("Fin");

          jLabel1.setText("Total:");

          totalLabel.setText("0");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(mostrarButton)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(Inicio)
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(Inicio1)
                                             .addComponent(fechaFinText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(0, 321, Short.MAX_VALUE))
                         .addComponent(jScrollPane1))
                    .addContainerGap())
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGap(16, 16, 16)
                         .addComponent(fechaIniText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(430, Short.MAX_VALUE)))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(Inicio)
                         .addComponent(Inicio1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fechaFinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(mostrarButton)
                    .addGap(15, 15, 15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(totalLabel))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addContainerGap())
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGap(25, 25, 25)
                         .addComponent(fechaIniText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(389, Short.MAX_VALUE)))
          );

          bindingGroup.bind();

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void mostrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarButtonActionPerformed
          registros.clear();
		try {
			List<RegistroVehiculo> listado = reporteador.obtenerReporte2(fechaIniText.getText(), fechaFinText.getText());
			registros.addAll(listado);
			double total = reporteador.obtenerSumaTotales(listado);
			this.totalLabel.setText(Double.toString(total));
			
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
		
		
     }//GEN-LAST:event_mostrarButtonActionPerformed

	public ObservableList<RegistroVehiculo> getRegistros() {
		return registros;
	}

	public void setRegistros(ObservableList<RegistroVehiculo> registros) {
		this.registros = registros;
	}

	


	
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel Inicio;
     private javax.swing.JLabel Inicio1;
     private javax.swing.JFormattedTextField fechaFinText;
     private javax.swing.JFormattedTextField fechaIniText;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable jTable1;
     private javax.swing.JButton mostrarButton;
     private javax.swing.JLabel totalLabel;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables
}
