/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueo.gui.frames.registros;

import java.util.ArrayList;
import java.util.List;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import parqueo.backend.modelos.registros.RegistroVehiculo;
import parqueo.backend.parqueo.ManejadorParqueo;

/**
 *
 * @author jose
 */
public class ListadoRegistrosInternalFrame extends javax.swing.JInternalFrame {

	private ManejadorParqueo manejadorParqueo;
	private List<RegistroVehiculo> registrosList;
	private ObservableList<RegistroVehiculo> registros;

	/**
	 * Creates new form ListadoRegistrosInternalFrame
	 *
	 * @param manejador
	 */
	public ListadoRegistrosInternalFrame(ManejadorParqueo manejador) {
		this.manejadorParqueo = manejador;
		registrosList = new ArrayList<>();
		registros = ObservableCollections.observableList(registrosList);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          verCombo = new javax.swing.JComboBox<>();
          buscarButton = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          jTable1 = new javax.swing.JTable();

          setClosable(true);
          setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
          setIconifiable(true);
          setMaximizable(true);
          setResizable(true);
          setTitle("Listado de registros");

          jLabel1.setText("Ver:");

          verCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Abiertos", "Cerrados" }));

          buscarButton.setText("Buscar");
          buscarButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buscarButtonActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(verCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarButton)
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(verCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(buscarButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${registros}");
          org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
          org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaIngreso}"));
          columnBinding.setColumnName("Fecha Ingreso");
          columnBinding.setColumnClass(java.time.LocalDate.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliente.NIT}"));
          columnBinding.setColumnName("Cliente");
          columnBinding.setColumnClass(String.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${placa}"));
          columnBinding.setColumnName("Placa");
          columnBinding.setColumnClass(String.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoVehiculoStr}"));
          columnBinding.setColumnName("Tipo vehiculo");
          columnBinding.setColumnClass(String.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horasParqueadas}"));
          columnBinding.setColumnName("Horas Parqueadas");
          columnBinding.setColumnClass(Double.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${subtotal}"));
          columnBinding.setColumnName("Subtotal");
          columnBinding.setColumnClass(Double.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${conDescuento}"));
          columnBinding.setColumnName("Con Descuento");
          columnBinding.setColumnClass(Boolean.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total}"));
          columnBinding.setColumnName("Total");
          columnBinding.setColumnClass(Double.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estado}"));
          columnBinding.setColumnName("Estado");
          columnBinding.setColumnClass(String.class);
          columnBinding.setEditable(false);
          columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${antiguedad}"));
          columnBinding.setColumnName("Antiguedad");
          columnBinding.setColumnClass(Boolean.class);
          bindingGroup.addBinding(jTableBinding);
          jTableBinding.bind();
          jScrollPane1.setViewportView(jTable1);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap())
          );

          bindingGroup.bind();

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
		actualizarListadoRegistros(manejadorParqueo.buscarRegistros(verCombo.getSelectedIndex()));
     }//GEN-LAST:event_buscarButtonActionPerformed

	private void actualizarListadoRegistros(List<RegistroVehiculo> listado) {
		registros.clear();
		registros.addAll(listado);
	}

	public ObservableList<RegistroVehiculo> getRegistros() {
		return registros;
	}

	public void setRegistros(ObservableList<RegistroVehiculo> registros) {
		this.registros = registros;
	}


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton buscarButton;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable jTable1;
     private javax.swing.JComboBox<String> verCombo;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables
}
