package parqueo.gui.frames.registros;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import javax.swing.JOptionPane;
import parqueo.backend.excepciones.ValidacionExcepcion;
import parqueo.backend.modelos.parqueo.Parqueo;
import parqueo.backend.modelos.personas.Cliente;
import parqueo.backend.modelos.registros.RegistroVehiculo;
import parqueo.backend.parqueo.ManejadorParqueo;
import parqueo.backend.personas.clientes.ManejadorClientes;

/**
 *
 * @author jose
 */
public class RegistroSalidaDialog extends javax.swing.JDialog {

	private RegistroVehiculo registro;
	ManejadorParqueo manejadorParqueo;

	/**
	 * Creates new form RegistroIngresoDialog
	 *
	 * @param parent
	 * @param manejadorParqueo
	 * @param manejadorClientes
	 */
	public RegistroSalidaDialog(java.awt.Frame parent, ManejadorParqueo manejadorParqueo) {
		super(parent, true);
		this.manejadorParqueo = manejadorParqueo;
		initComponents();
	}

	public void mostrarDialogo() {
		limpiarData();
		registro = null;
		this.setLocationRelativeTo(this.getParent());
		this.setVisible(true);
	}

	public RegistroVehiculo getRegistro() {
		return registro;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          tipoVehiculoLabel = new javax.swing.JLabel();
          tipoVehiculoCombo = new javax.swing.JComboBox<>();
          nitLabel = new javax.swing.JLabel();
          nitText = new javax.swing.JTextField();
          placaLabel = new javax.swing.JLabel();
          placaText = new javax.swing.JTextField();
          retirarButton = new javax.swing.JButton();
          fechaIngresoLabel = new javax.swing.JLabel();
          fechaIngresoText = new javax.swing.JFormattedTextField();
          fechaEjemploLabel = new javax.swing.JLabel();
          horasText = new javax.swing.JFormattedTextField();
          jLabel1 = new javax.swing.JLabel();

          setTitle("Registro de salida");
          setResizable(false);

          tipoVehiculoLabel.setText("Vehiculo:");

          tipoVehiculoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto", "Carro", "Camion" }));

          nitLabel.setText("NIT del cliente:");

          placaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          placaLabel.setText("Placa:");

          retirarButton.setText("Retirar vehiculo");
          retirarButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    retirarButtonActionPerformed(evt);
               }
          });

          fechaIngresoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          fechaIngresoLabel.setText("Fecha ingreso:");

          try {
               fechaIngresoText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
          } catch (java.text.ParseException ex) {
               ex.printStackTrace();
          }
          fechaIngresoText.setPreferredSize(new java.awt.Dimension(14, 23));

          fechaEjemploLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
          fechaEjemploLabel.setText("(e.j. 31/02/1980)");

          horasText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
          horasText.setMinimumSize(new java.awt.Dimension(4, 23));
          horasText.setPreferredSize(new java.awt.Dimension(135, 23));

          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          jLabel1.setText("Horas:");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(retirarButton))
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(fechaIngresoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(fechaEjemploLabel)
                                   .addComponent(fechaIngresoText, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                   .addComponent(horasText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGap(0, 129, Short.MAX_VALUE))
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                   .addComponent(placaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(nitLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(tipoVehiculoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(tipoVehiculoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(nitText)
                                   .addComponent(placaText))))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(tipoVehiculoLabel)
                         .addComponent(tipoVehiculoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(nitLabel)
                         .addComponent(nitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(placaLabel)
                         .addComponent(placaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(fechaIngresoLabel)
                         .addComponent(fechaIngresoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fechaEjemploLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(horasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addComponent(retirarButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void retirarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarButtonActionPerformed
		try {
			registro = manejadorParqueo.retirarVehiculo(tipoVehiculoCombo.getSelectedIndex(),
				   nitText.getText(), placaText.getText(), fechaIngresoText.getText(),
				   horasText.getText());
			setVisible(false);
		} catch (ValidacionExcepcion ex) {
			registro = null;
			JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}

     }//GEN-LAST:event_retirarButtonActionPerformed

	public void limpiarData() {
		nitText.setText("");
		placaText.setText("");
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern(Parqueo.FORMATO_FECHA);
		fechaIngresoText.setText(LocalDate.now().format(formatter));
	}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel fechaEjemploLabel;
     private javax.swing.JLabel fechaIngresoLabel;
     private javax.swing.JFormattedTextField fechaIngresoText;
     private javax.swing.JFormattedTextField horasText;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel nitLabel;
     private javax.swing.JTextField nitText;
     private javax.swing.JLabel placaLabel;
     private javax.swing.JTextField placaText;
     private javax.swing.JButton retirarButton;
     private javax.swing.JComboBox<String> tipoVehiculoCombo;
     private javax.swing.JLabel tipoVehiculoLabel;
     // End of variables declaration//GEN-END:variables
}
