package parqueo.gui.frames.registros;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import parqueo.backend.excepciones.ValidacionExcepcion;
import parqueo.backend.modelos.parqueo.Parqueo;
import parqueo.backend.modelos.personas.Cliente;
import parqueo.backend.modelos.registros.RegistroVehiculo;
import parqueo.backend.parqueo.ManejadorParqueo;
import parqueo.backend.personas.clientes.ManejadorClientes;

/**
 *
 * @author jose
 */
public class RegistroIngresoDialog extends javax.swing.JDialog {

	private RegistroVehiculo registro;
	ManejadorClientes manejadorClientes;
	ManejadorParqueo manejadorParqueo;

	/**
	 * Creates new form RegistroIngresoDialog
	 *
	 * @param parent
	 * @param manejadorParqueo
	 * @param manejadorClientes
	 */
	public RegistroIngresoDialog(java.awt.Frame parent, ManejadorParqueo manejadorParqueo,
		   ManejadorClientes manejadorClientes) {
		super(parent, true);
		this.manejadorClientes = manejadorClientes;
		this.manejadorParqueo = manejadorParqueo;
		initComponents();
	}

	public void mostrarDialogo() {
		limpiarData();
		registro = null;
		habilitarInputs(false);
		this.setLocationRelativeTo(this.getParent());
		this.setVisible(true);
	}

	public RegistroVehiculo getRegistro() {
		return registro;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          tipoVehiculoLabel = new javax.swing.JLabel();
          tipoVehiculoCombo = new javax.swing.JComboBox<>();
          verificarButton = new javax.swing.JButton();
          nitLabel = new javax.swing.JLabel();
          nitText = new javax.swing.JTextField();
          placaLabel = new javax.swing.JLabel();
          placaText = new javax.swing.JTextField();
          ingresarButton = new javax.swing.JButton();
          fechaIngresoLabel = new javax.swing.JLabel();
          fechaIngresoText = new javax.swing.JFormattedTextField();
          fechaEjemploLabel = new javax.swing.JLabel();

          setTitle("Registro de ingreso");
          setResizable(false);

          tipoVehiculoLabel.setText("Vehiculo a ingresar:");

          tipoVehiculoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto", "Carro", "Camion" }));
          tipoVehiculoCombo.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    tipoVehiculoComboActionPerformed(evt);
               }
          });

          verificarButton.setText("Verificar espacio");
          verificarButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    verificarButtonActionPerformed(evt);
               }
          });

          nitLabel.setText("NIT del cliente:");

          nitText.setEnabled(false);
          nitText.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusLost(java.awt.event.FocusEvent evt) {
                    nitTextFocusLost(evt);
               }
          });

          placaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          placaLabel.setText("Placa:");

          placaText.setEnabled(false);

          ingresarButton.setText("Ingresar");
          ingresarButton.setEnabled(false);
          ingresarButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ingresarButtonActionPerformed(evt);
               }
          });

          fechaIngresoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          fechaIngresoLabel.setText("Fecha ingreso:");

          try {
               fechaIngresoText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
          } catch (java.text.ParseException ex) {
               ex.printStackTrace();
          }
          fechaIngresoText.setEnabled(false);
          fechaIngresoText.setPreferredSize(new java.awt.Dimension(14, 23));

          fechaEjemploLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
          fechaEjemploLabel.setText("(e.j. 31/02/1980)");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(tipoVehiculoLabel)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(tipoVehiculoCombo, 0, 243, Short.MAX_VALUE))
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                   .addComponent(placaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(nitLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(nitText)
                                   .addComponent(placaText)))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(fechaIngresoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(fechaEjemploLabel)
                                   .addComponent(fechaIngresoText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(0, 0, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(verificarButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(ingresarButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(tipoVehiculoLabel)
                         .addComponent(tipoVehiculoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(verificarButton)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(nitLabel)
                         .addComponent(nitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(placaLabel)
                         .addComponent(placaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(fechaIngresoLabel)
                         .addComponent(fechaIngresoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fechaEjemploLabel)
                    .addGap(24, 24, 24)
                    .addComponent(ingresarButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void verificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarButtonActionPerformed
		if (manejadorParqueo.verificarEspacio(tipoVehiculoCombo.getSelectedIndex())) {
			habilitarInputs(true);
		} else {
			JOptionPane.showMessageDialog(this.getParent(), "No hay espacio para este vehiculo", "Info", JOptionPane.WARNING_MESSAGE);
		}
     }//GEN-LAST:event_verificarButtonActionPerformed

     private void tipoVehiculoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVehiculoComboActionPerformed
		habilitarInputs(false);
     }//GEN-LAST:event_tipoVehiculoComboActionPerformed

     private void ingresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButtonActionPerformed
		try {
			registro = manejadorParqueo.registrarVehiculo(tipoVehiculoCombo.getSelectedIndex(),
				   nitText.getText(), placaText.getText(), fechaIngresoText.getText(),
				   manejadorClientes);
			setVisible(false);
		} catch (ValidacionExcepcion ex) {
			registro = null;
			JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}
     }//GEN-LAST:event_ingresarButtonActionPerformed

     private void nitTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nitTextFocusLost
		Cliente cliente = manejadorClientes.buscarPorNIT(nitText.getText());
		if (cliente == null && !nitText.getText().isEmpty()) {
			JOptionPane.showMessageDialog(this.getParent(),
				   "No existe cliente con ese NIT:" + nitText.getText(), "Error",
				   JOptionPane.ERROR_MESSAGE);
			nitText.setText("");
		}
     }//GEN-LAST:event_nitTextFocusLost

	public void habilitarInputs(boolean habilitar) {
		nitText.setEnabled(habilitar);
		placaText.setEnabled(habilitar);
		fechaIngresoText.setEnabled(habilitar);
		ingresarButton.setEnabled(habilitar);
	}

	public void limpiarData() {
		nitText.setText("");
		placaText.setText("");
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern(Parqueo.FORMATO_FECHA);
		fechaIngresoText.setText(LocalDate.now().format(formatter));
	}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel fechaEjemploLabel;
     private javax.swing.JLabel fechaIngresoLabel;
     private javax.swing.JFormattedTextField fechaIngresoText;
     private javax.swing.JButton ingresarButton;
     private javax.swing.JLabel nitLabel;
     private javax.swing.JTextField nitText;
     private javax.swing.JLabel placaLabel;
     private javax.swing.JTextField placaText;
     private javax.swing.JComboBox<String> tipoVehiculoCombo;
     private javax.swing.JLabel tipoVehiculoLabel;
     private javax.swing.JButton verificarButton;
     // End of variables declaration//GEN-END:variables
}
